### ISSUE TITLE
AddConsole logging on ubuntu 14.04 gives PlatformNotSuportedException

### ISSUE THREAD

**Issue by IRooc** [aspnet/Logging#202]
When I run the SampleApp in this repro on Ubuntu 14.04 using coreclr x64 1.0.0-beta6-12120 the following exception is thrown:
```
System.PlatformNotSupportedException: This platform does not support getting the current color.
   at System.ConsolePal.get_ForegroundColor()
   at Microsoft.Framework.Logging.Console.LogConsole.get_ForegroundColor()
   at Microsoft.Framework.Logging.Console.ConsoleLogger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   at Microsoft.Framework.Logging.Logger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   at SampleApp.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
```

On Windows it works fine using the same coreclr x64 version

**Comment by BrennanConroy** [comment]
18e367d36f2dac1e5072fa746590da85a779c5c5
