### ISSUE TITLE
(EventLog)Logger does not catch exceptions internally and is able to crash the application

### ISSUE THREAD

**Issue by Mertsch** [aspnet/Logging#304]
I encountered an error today which prevents me from writing to the database, because the logger throws an exception while logging.
Should we consider making logging more robust and never throw exceptions to the caller that relate purely to the logging itself?

Note: I will report the size violation in a separate Issue.
```
Microsoft.Data.Entity.DbContext
An exception occurred in the database while saving changes.
Microsoft.Data.Entity.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.AggregateException: An error occurred while writing to logger(s). ---> System.ArgumentException: Log entry string is too long. A string written to the event log cannot exceed 32766 characters.
   at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventLogEntryType type, String[] strings, Byte[] rawData, String currentMachineName)
   at System.Diagnostics.EventLogInternal.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData)
   at System.Diagnostics.EventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category)
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   at Microsoft.Data.Entity.Infrastructure.SensitiveDataLogger`1.Microsoft.Extensions.Logging.ILogger.Log(LogLevel logLevel, Int32 eventId, Object state, Exception exception, Func`3 formatter)
   at Microsoft.Data.Entity.Storage.RelationalLoggerExtensions.LogInformation[TState](ILogger logger, RelationalLoggingEventId eventId, Func`1 state, Func`2 formatter)
   at Microsoft.Data.Entity.Storage.RelationalLoggerExtensions.LogCommandExecuted(ISensitiveDataLogger logger, DbCommand command, Nullable`1 elapsedMilliseconds)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.<ExecuteAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.<ExecuteReaderAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Data.Entity.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__28.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Entity.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Data.Entity.Update.Internal.BatchExecutor.<ExecuteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Data.Entity.DbContext.<SaveChangesAsync>d__28.MoveNext()
```

**Comment by Eilon** [comment]
I think we've debated this before and decided it might be best to allow it to blow up. At least, that's where I stand on this.

The problem with a faulty logger is that you have nowhere to log the failure (duh :smile: ). And if the failure is hidden from all observers, a faulty logger will possibly never be discovered.

**Comment by Mertsch** [comment]
Yeah, I totally agree.
But some things to take into consideration ...

In this case I am loosing data, as a critical DB operation fails because a log can't be written -_-

You can have multiple loggers, so a failing logger does not necessarily mean that you lose the log info

How about a logger exception handler? Meaning if logger fails and user did not register specific action for handling those, throw, otherwise let the user decide

Thanks for reading

**Comment by muratg** [comment]
I agree with @Eilon on this that the logger should not eat exceptions silently.  

Which logger are you using here?  Perhaps we can harden (maybe with retries)...

**Comment by Eilon** [comment]
One could certainly implement their own *wrapping* loggers that have extra fault tolerance...

**Comment by Mertsch** [comment]
@muratg In my case it was the EventlogLogger see https://github.com/aspnet/Logging/issues/305

**Comment by muratg** [comment]
@Mertsch I see. I think writing a wrapper around that for your specific usage would be the better option here.  Your Logger would trim your messages (or divide them into multiple log objects, for example) and would eat any other exceptions as required for your app.

**Comment by muratg** [comment]
We'll be changing the event log logging provider (for #305) for the specific issue, but we won't be in general catching and swallowing exceptions in all loggers by default.  Closing this one.
