### ISSUE TITLE
Loggers throw on null message or arguments

### ISSUE THREAD

**Issue by cesarbs** [aspnet/Logging#422]
Part of https://github.com/aspnet/Release/issues/31

`Log*(null)` or `Log*("{0}", null)` makes the logger throw:

    Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.Extensions.Logging.Internal.FormattedLogValues..ctor(String format, Object[] values)
       at Microsoft.Extensions.Logging.LoggerExtensions.LogTrace(ILogger logger, String message, Object[] args)
       at WebApplicationLoggingNetFramework.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory) in C:\Users\cesars\Documents\Visual Studio 2015\Projects\WebApplicationLoggingNetFramework\src\WebApplicationLoggingNetFramework\Startup.cs:line 32
       --- End of inner exception stack trace ---
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at Microsoft.AspNetCore.Hosting.Startup.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
       at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
       at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()

Logging should be more resilient to this. Print `(null)` or something similar when a null is logged.

**Comment by muratg** [comment]
I think this is a dup of https://github.com/aspnet/Logging/issues/335

@cesarbs is this implementation specific or does it repro regardless of the provider?

**Comment by cesarbs** [comment]
@muratg Seems to repro regardless of provider. Notice there's no particular provider in the stack trace.

**Comment by cesarbs** [comment]
[Current agreement](https://github.com/aspnet/Logging/issues/335#issuecomment-200669693) is that logging abstractions should not swallow logger exceptions.

We should still harden our loggers (Console, Debug, etc.) against `null`s.
