### ISSUE TITLE
'Log' does not have an implementation error after RC2 upgrade

### ISSUE THREAD

**Issue by rbjarnason** [aspnet/Logging#433]
I'm working on upgrading from RC1 to RC2 and after a lot of relatively painful work ;) I have everything compiling. But when I try to run the app with "dotnet run" I get this error:
```
Unhandled Exception: System.TypeLoadException: Method 'Log' in type
'Microsoft.Extensions.Logging.Logger' from 
assembly 'Microsoft.Extensions.Logging, 
Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' 
does not have an implementation.
   at Microsoft.Extensions.Logging.LoggerFactory..ctor()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at ak_admin_spa.Program.Main(String[] args) in 
C:\Projects\ak-admin-spa\src\ak-admin-spa\Startup.cs:line 141
```

Startup():
```
 Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .Enrich.FromLogContext()
                .WriteTo.Seq("http://localhost:5341")
                .CreateLogger();
```

ConfigureServices():
```
  services.AddLogging();
```

Configure():
```
  loggerFactory.AddConsole();
  loggerFactory.AddSerilog();
```

Main():
```
  var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();
  host.Run();
```

dotnet --info:
```
.NET Command Line Tools (1.0.0-preview2-002817)

Product Information:
 Version:            1.0.0-preview2-002817
 Commit SHA-1 hash:  9155fbfbdb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
```

Any hints?

project.json:

```json
{
  "webroot": "wwwroot_ra_admin",
  "version": "1.0.0-*",
  "dependencies": {
    "Microsoft.NETCore.Platforms": "1.0.1-rc2-24027",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.WebListener": "0.1.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Session": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "System.Net.Http": "4.0.1-beta-23409",
    "System.ServiceModel": "1.0.0",
    "System.Linq": "4.1.0-rc2-24027",
    "NETStandard.Library": "1.5.0-rc2-24027",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Xml": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Http": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc.WebApiCompatShim": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.TraceSource": "1.0.0-rc2-final",
    "log4net": "2.0.5",
    "iTextSharp": "5.5.9",
    "RestSharp": "105.2.3",
    "Spire.PDF": "3.7.0",
    "Microsoft.EntityFrameworkCore.Tools.Core": "1.0.0-rc2-final",
    "System.ComponentModel": "4.0.1-rc2-24027",
    "Serilog": "2.0.0-rc-556",
    "Serilog.Extensions.Logging": "1.0.0-rc2-10104",
    "Serilog.Sinks.Seq": "2.0.0-rc-46"
  },
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "runtimeOptions": {
    "gcServer": false,
    "gcConcurrent": true
  },
  "frameworks": {
    "net451": {
      "dependencies": {
        "ADSS-Client-API": "1.0.0-*"
      },
      "frameworkAssemblies": {
        "System.Data": "4.0.0.0",
        "System.Runtime": "4.0.10.0",
        "System.Data.Linq": "4.0.0.0",
        "System.Web": "4.0.0.0",
        "System.Configuration": "4.0.0.0",
        "System.Data.Entity": "4.0.0.0",
        "System.ServiceModel": "4.0.0.0",
        "System.Drawing": "4.0.0.0",
        "System.DirectoryServices": "4.0.0.0",
        "System.DirectoryServices.AccountManagement": "4.0.0.0",
        "System.DirectoryServices.Protocols": "4.0.0.0"
      }
    }
  },
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-*",
      "imports": "portable-net45+wp80+win10+wpa81+dnxcore50"
    }
  },
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  },
  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "configurations": {
    "AkRaDebug": { },
    "AkRaDebugTwo": { }
  },
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  }
}
```

**Comment by davidfowl** [comment]
One of your dependencies is built against an older version of the logging package

**Comment by rbjarnason** [comment]
@davidfowl Thanks but I'm not sure which one.  I had Microsoft.Extensions.Logging at rc1 but I fixed that and it now points to rc2.  What else could be wrong?

**Comment by davidfowl** [comment]
I'd suggesting removing dependencies until you find the problem. You could also analyze the `project.lock.json` file to see which of your dependencies are dependent on the rc1 version of logging.       l.l

**Comment by rbjarnason** [comment]
Here is everything from my .lock file to do with serilog:
```
 "Serilog/2.0.0-rc-556": {
        "type": "package",
        "compile": {
          "lib/net45/Serilog.dll": {}
        },
        "runtime": {
          "lib/net45/Serilog.dll": {}
        }
      },
      "Serilog.Extensions.Logging/1.0.0-rc2-10104": {
        "type": "package",
        "dependencies": {
          "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
          "Serilog": "2.0.0-rc-556"
        },
        "frameworkAssemblies": [
          "System.Runtime"
        ],
        "compile": {
          "lib/net45/Serilog.Extensions.Logging.dll": {}
        },
        "runtime": {
          "lib/net45/Serilog.Extensions.Logging.dll": {}
        }
      },
      "Serilog.Sinks.File/2.0.0-rc-704": {
        "type": "package",
        "dependencies": {
          "Serilog": "2.0.0-rc-556"
        },
        "compile": {
          "lib/net45/Serilog.Sinks.File.dll": {}
        },
        "runtime": {
          "lib/net45/Serilog.Sinks.File.dll": {}
        }
      },
      "Serilog.Sinks.PeriodicBatching/2.0.0-rc-707": {
        "type": "package",
        "dependencies": {
          "Serilog": "2.0.0-rc-556"
        },
        "compile": {
          "lib/net45/Serilog.Sinks.PeriodicBatching.dll": {}
        },
        "runtime": {
          "lib/net45/Serilog.Sinks.PeriodicBatching.dll": {}
        }
      },
      "Serilog.Sinks.RollingFile/2.0.0-rc-703": {
        "type": "package",
        "dependencies": {
          "Serilog": "2.0.0-rc-556",
          "Serilog.Sinks.File": "2.0.0-rc-704"
        },
        "compile": {
          "lib/net45/Serilog.Sinks.RollingFile.dll": {}
        },
        "runtime": {
          "lib/net45/Serilog.Sinks.RollingFile.dll": {}
        }
      },
      "Serilog.Sinks.Seq/2.0.0-rc-46": {
        "type": "package",
        "dependencies": {
          "Serilog": "2.0.0-rc-556",
          "Serilog.Sinks.PeriodicBatching": "2.0.0-rc-707",
          "Serilog.Sinks.RollingFile": "2.0.0-rc-703"
        },
        "frameworkAssemblies": [
          "System.Net.Http"
        ],
        "compile": {
          "lib/net45/Serilog.Sinks.Seq.dll": {}
        },
        "runtime": {
          "lib/net45/Serilog.Sinks.Seq.dll": {}
        }
      },
```     

I also have log4net, could that be conflicting?
```
      "log4net/2.0.5": {
        "type": "package",
        "compile": {
          "lib/net45-full/log4net.dll": {}
        },
        "runtime": {
          "lib/net45-full/log4net.dll": {}
        }
      },
```

**Comment by rbjarnason** [comment]
There is no mention of rc1 in my lock file.

**Comment by davidfowl** [comment]
log4net can't clash with Microsoft.Extensions.Logging. Can you try to narrow it down by removing dependencies? Also, can you share the entire lock file?

**Comment by rbjarnason** [comment]
Here is the whole file: https://gist.github.com/rbjarnason/3f6b7ea9f721def950b276cea5e236aa

**Comment by rbjarnason** [comment]
@davidfowl I could try removing dependencies but its a large app and removing dependencies will break the code so it would be quite time consuming...

**Comment by davidfowl** [comment]
You have to spend time somewhere. I honestly can't tell you why it's not working. The lock file looks fine but the type mismatch suggest that the logging in your output folder is older.

**Comment by rbjarnason** [comment]
So what I have so far is that I have removed serilog first, then Microsoft.Extensions.Logging then a couple of other things but still get the same error.  And have commented everything logging related from Startup.cs. Now the only items with log in their name in the .lock file are the log4net.

**Comment by davidfowl** [comment]
@rbjarnason And you tried clearing out the bin folder or making a new project with the same dependencies to see if you can reproduce?

**Comment by rbjarnason** [comment]
Thanks @davidfowl :) removing the bin folder and get everything rebuilt, I get the app to get past this problem.

I'm now stuck on "System.DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found." I saw you were discussing this in another unrelated ticket, I will ping you there if I don't figure it out.

**Comment by rbjarnason** [comment]
@davidfowl Got the app running, thanks again for your help.
