### ISSUE TITLE
InvalidOperationException: Configuration value 'Verbose' for category 'Default' is not supported in AuthenticationMiddleware ctr

### ISSUE THREAD

**Issue by ivankarpey** [aspnet/Logging#436]
this is for rc2 version of code.

If there is this line in `Startup.Configure`

`loggerFactory.AddConsole(Configuration.GetSection("Logging"));` `// It's exist there by default btw`

than Implementation of `AuthenticationMiddleware` throws `InvalidOperationException` when call base class constructor. `"Configuration value 'Verbose' for category 'Default' is not supported."`

Stacktrace:
```
at Microsoft.Extensions.Logging.Console.ConfigurationConsoleLoggerSettings.TryGetSwitch(String name, LogLevel& level)
   at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider.GetFilter(String name, IConsoleLoggerSettings settings)
   at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider.CreateLoggerImplementation(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.Logging.Logger..ctor(LoggerFactory loggerFactory, String name)
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1..ctor(RequestDelegate next, IOptions`1 options, ILoggerFactory loggerFactory, UrlEncoder encoder)
   at Test.AuthMiddleware..ctor(RequestDelegate next, IOptions`1 options, ILoggerFactory loggerFactory, UrlEncoder encoder)
```

**Comment by muratg** [comment]
@ivankarpey what does the `Logging` section in your configuration look like?

**Comment by ivankarpey** [comment]
```
"Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Verbose",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
```

**Comment by 304NotModified** [comment]
Well Verbose is RC1, and removed in RC2

**Comment by muratg** [comment]
@304NotModified is right.  Either use `Debug` or `Trace`. Please file another one if that doesn't solve the issue!

**Comment by wpostma** [comment]
This seems like a user-unfriendly behaviour since other Microsoft logging frameworks have always supported "Verbose".

I'd rather see it translate "Verbose" as an alias to "Debug" for me, than terminate my startup if someone tried to use values the obtained after googling and hitting this page:

https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.diagnostics.loglevel.aspx

**Comment by muratg** [comment]
@wpostma We have looked into several logging frameworks and user feedback through RC1 to decide on the log levels. 

Not sure how "translating" would work at all?  In any case, since we RTM'd, we won't be changing the public API surface.
