### ISSUE TITLE
Library throws fatal error exception when running a project that has regular/normal .net references

### ISSUE THREAD

**Issue by jlVidal** [aspnet/Logging#569]
I'm unable to run an ASP.NET Core project that has regular .NET references. Exception:

```
 HResult=-2147467262
       Message=Unable to cast object of type 'System.Configuration.Internal.ConfigurationManagerInternal' to type 'System.Configuration.TimeSpanValidator'.
       Source=System
       StackTrace:
            at System.Configuration.ConfigurationManagerInternalFactory.get_Instance()
            at System.Diagnostics.DiagnosticsConfiguration.Initialize()
            at System.Diagnostics.DiagnosticsConfiguration.get_IndentSize()
            at System.Diagnostics.TraceInternal.InitializeSettings()
            at System.Diagnostics.TraceInternal.WriteLine(String message, String category)
            at Microsoft.Extensions.Logging.Debug.DebugLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
            at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
       InnerException: 

```
More details:
http://stackoverflow.com/questions/42727684/asp-net-core-startup-fatal-error-impossible-to-run-the-project-with-normal-ne

**Comment by davidfowl** [comment]
Seems to have something to do with the configuration being readonly. Can you reproduce this on a new project? If so , can you put it on github so we can reproduce the issue?

**Comment by jlVidal** [comment]
Sorry I couldn't reproduce the issue, it was solved once I re-created my projects, update my dependencies, and nuget package for latest libraries versions
